# Generated by Django 5.0.7 on 2024-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=122)),
                ('car_company', models.CharField(max_length=122)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_year', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
