# Generated by Django 5.0.7 on 2024-12-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images/'),
        ),
    ]
