# Generated by Django 5.0.7 on 2024-12-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_first_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
