# Generated by Django 5.0.7 on 2024-12-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_first_app', '0004_cars_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='registration_number',
        ),
    ]
