# Generated by Django 5.0.7 on 2024-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_first_app', '0005_remove_cars_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='engine_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='registration_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
